### ISSUE TITLE
windows10下docker运行报错

### ISSUE THREAD

**Issue by EchoRiver** [jarvis2f/telegram-files#1]
2024-12-26 17:54:48 telegram-files  | Using TDLib from /app/tdlib/libs/linux_x64
2024-12-26 17:54:48 telegram-files  | pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
2024-12-26 17:54:48 telegram-files  | 2024-12-26T09:54:48: PM2 log: Launching in no daemon mode
2024-12-26 17:54:48 telegram-files  | 2024-12-26T09:54:48: PM2 log: [PM2][WARN] Applications telegram-files-web not running, starting...
2024-12-26 17:54:48 telegram-files  | 2024-12-26T09:54:48: PM2 log: App [telegram-files-web:0] starting in -cluster mode-
2024-12-26 17:54:48 telegram-files  | 2024-12-26T09:54:48: PM2 log: App [telegram-files-web:0] online
2024-12-26 17:54:48 telegram-files  | 2024-12-26T09:54:48: PM2 log: [PM2] App [telegram-files-web] launched (1 instances)
2024-12-26 17:54:48 telegram-files  | 2024-12-26T09:54:48: PM2 log: ┌────┬───────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
2024-12-26 17:54:48 telegram-files  | │ id │ name                  │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
2024-12-26 17:54:48 telegram-files  | ├────┼───────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
2024-12-26 17:54:48 telegram-files  | │ 0  │ telegram-files-web    │ default     │ 0.1.4   │ cluster │ 46       │ 0s     │ 0    │ online    │ 0%       │ 51.1mb   │ root     │ disabled │
2024-12-26 17:54:48 telegram-files  | └────┴───────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
2024-12-26 17:54:48 telegram-files  | 2024-12-26T09:54:48: PM2 log: [--no-daemon] Continue to stream logs
2024-12-26 17:54:48 telegram-files  | 2024-12-26T09:54:48: PM2 log: [--no-daemon] Exit on target PM2 exit pid=10
2024-12-26 17:54:48 telegram-files  | [2024-12-26 09:54:48] [SEVERE] ?Start failed 
2024-12-26 17:54:48 telegram-files  | 
2024-12-26 17:54:48 telegram-files  | java.lang.ExceptionInInitializerError
2024-12-26 17:54:48 telegram-files  | at telegram.files.DataVerticle.getDataPath(DataVerticle.java:70)
2024-12-26 17:54:48 telegram-files  | at telegram.files.DataVerticle.start(DataVerticle.java:37)
2024-12-26 17:54:48 telegram-files  | at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:210)
2024-12-26 17:54:48 telegram-files  | at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
2024-12-26 17:54:48 telegram-files  | at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)
2024-12-26 17:54:48 telegram-files  | at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)
2024-12-26 17:54:48 telegram-files  | at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
2024-12-26 17:54:48 telegram-files  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
2024-12-26 17:54:48 telegram-files  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
2024-12-26 17:54:48 telegram-files  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
2024-12-26 17:54:48 telegram-files  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2024-12-26 17:54:48 telegram-files  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-12-26 17:54:48 telegram-files  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-12-26 17:54:48 telegram-files  | at java.base/java.lang.Thread.run(Unknown Source)
2024-12-26 17:54:48 telegram-files  | Caused by: java.lang.RuntimeException: TELEGRAM_API_ID is not set
2024-12-26 17:54:48 telegram-files  | at telegram.files.Config.<clinit>(Config.java:36)
2024-12-26 17:54:48 telegram-files  | ... 14 more
2024-12-26 17:54:48 telegram-files  | 
2024-12-26 17:54:48 telegram-files  | 09:54:48 0|telegram-files-web  |    ▲ Next.js 15.0.3
2024-12-26 17:54:48 telegram-files  | 09:54:48 0|telegram-files-web  |    - Local:        http://localhost:3000
2024-12-26 17:54:48 telegram-files  | 09:54:48 0|telegram-files-web  |    - Network:      http://0.0.0.0:3000
2024-12-26 17:54:48 telegram-files  | 09:54:48 0|telegram-files-web  |  ✓ Starting...
2024-12-26 17:54:48 telegram-files  | 09:54:48 0|telegram-files-web  |  ✓ Ready in 172ms

**Comment by greatislee** [comment]
Linux  x86_64  docker same error

**Comment by jarvis2f** [comment]
TELEGRAM_API_ID: ${TELEGRAM_API_ID}
TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
需要申请一下Telegram的api_id

Sign up for Telegram using an official application.
Log in to your Telegram core: https://my.telegram.org/.
Go to ["API development tools"](https://my.telegram.org/apps) and fill out the form.
You will get basic addresses as well as the api_id and api_hash parameters required for user authorization.
For the moment each number can only have one api_id connected to it.

**Comment by EchoRiver** [comment]
控制台报错 552-54e7537760dca10a.js:1 WebSocket connection to 'ws://localhost:6543/ws' failed: 
![Uploading 333.png…]()

**Comment by jarvis2f** [comment]
> 控制台报错 552-54e7537760dca10a.js:1 WebSocket connection to 'ws://localhost:6543/ws' failed:

docker里api服务启动失败应该

**Comment by EchoRiver** [comment]
> > 控制台报错 552-54e7537760dca10a.js:1 WebSocket connection to 'ws://localhost:6543/ws' failed:
> 
> docker里api服务启动失败应该

TELEGRAM_API_ID 和TELEGRAM_API_HASH都申请填了

**Comment by EchoRiver** [comment]
WebSocket connection to 'ws://localhost:6543/ws' failed: 
POST http://localhost:6543/api/telegrams/change?telegramId= 403 (CORS Rejected - Invalid origin)
浏览器Console里面报错，除了配置TELEGRAM_API_ID 和TELEGRAM_API_HASH 没别的了吧
services:
  telegram-files:
    container_name: telegram-files
    image: ghcr.io/jarvis2f/telegram-files:latest
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "--timeout=3", "--tries=1", "http://localhost:8080/health" ]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s
    environment:
      APP_ENV: ${APP_ENV:-prod}
      APP_ROOT: ${APP_ROOT:-/app/data}
      TELEGRAM_API_ID: xxxxx
      TELEGRAM_API_HASH: xxxxxxxxxxxxx
    ports:
      - "6543:80"
    volumes:
      - ./data:/app/data
